### ISSUE TITLE
Garage door opener open/close on boot

### ISSUE THREAD

**Issue by cben0ist** [johnboiles/homeassistant-config#3]
When I boot my ESP-01, the relay briefly contacts which cause the door to open or close (depending on door state indeed). Do you know any option to avoid the relay to do anything on boot?
Other than that, everything works perfectly!
Thanks

**Comment by johnboiles** [comment]
Huh my ESP01 doesn't do that, but I have a different problem. I'm using a bootstrap pin for the reed switch to determine open/closed. So my ESP01 fails to boot when the garage is closed 🤦 

Probably the ESP01 isn't a good choice for this.

**Comment by cben0ist** [comment]
I am not sure what happened at that time but after swapping the board with a new ESP-01 months later because the 1st one fried, I've got the same problem that you have now. I ended up switching to another one with more GPIOs (I can't remember which one I used now) and it works like a charm.
